@REM pip install setuptools wheel twine
@REM python setup.py sdist bdist_wheel
twine upload dist/termii_sdk-1.0*


@REM __token__
@REM pypi-AgEIcHlwaS5vcmcCJGFhOTJiOTg1LTFjZmUtNDczYi04MTk3LTM3OTA1ZTNjY2EyZAACElsxLFsidGVybWlpLXNkayJdXQACLFsyLFsiNWM3ODY5ODAtYmYyOC00YjMzLThiYTYtMTAyZjcyN2FiM2Y1Il1dAAAGIHj1eFieAtPh4WXt567mkzHYvfgzZnZxlpaglqWEvc0v
